version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: datadik
    container_name: appdatadik
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/datadik
    volumes:
      - .:/var/www/datadik
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-net

  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: nginxdatadik
    restart: always
    tty: true
    ports:
      - "127.0.0.1:8090:80"
    volumes:
      - .:/var/www/datadik
      - ./storage/:/etc/nginx/conf.d/
    networks:
      - app-net

#MySQL Service
  db:
    image: mysql:5.7
    container_name: dbdatadik
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      #MYSQL_DATABASE: datadik
      #MYSQL_USER: smeksa
      #MYSQL_PASSWORD: datadik123
      MYSQL_ROOT_PASSWORD: bintang123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - lbdata:/var/lib/mysql
    networks:
      - app-net

# phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8990:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: bintang123
    networks:
      - app-net

  #Docker Networks
networks:
  app-net:
    external: true

  #Volumes
volumes:
  lbdata:
    driver: local

